name: spreadit_crossplatform
description: "Reddit recreated, but cooler"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  google_sign_in_web : ^0.12.4
  dio: ^4.0.6
  build_runner: ^2.4.8
  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/LogoSpreadIt.png
  - assets/images/GoogleLogo.png
